spring:
  application:
    name: boot4-demo
  datasource:
    url: jdbc:h2:mem:demo
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
server:
  port: 8081
